// ═══════════════════════════════════════
// 风林慧策 — 股票数据库 (363 只)
// ═══════════════════════════════════════

var STOCK_DB = [
{c:"sh600519",n:"贵州茅台",m:"sh",mk:"ashare",s:"白酒"},
{c:"sh600600",n:"青岛啤酒",m:"sh",mk:"ashare",s:"白酒"},
{c:"sh600809",n:"山西汾酒",m:"sh",mk:"ashare",s:"白酒"},
{c:"sz000568",n:"泸州老窖",m:"sz",mk:"ashare",s:"白酒"},
{c:"sz000596",n:"古井贡酒",m:"sz",mk:"ashare",s:"白酒"},
{c:"sz000858",n:"五粮液",m:"sz",mk:"ashare",s:"白酒"},
{c:"sz002304",n:"洋河股份",m:"sz",mk:"ashare",s:"白酒"},
{c:"sh601318",n:"中国平安",m:"sh",mk:"ashare",s:"保险"},
{c:"sh601336",n:"新华保险",m:"sh",mk:"ashare",s:"保险"},
{c:"sh600048",n:"保利发展",m:"sh",mk:"ashare",s:"地产"},
{c:"sz000002",n:"万科A",m:"sz",mk:"ashare",s:"地产"},
{c:"sz001979",n:"招商蛇口",m:"sz",mk:"ashare",s:"地产"},
{c:"sh600050",n:"中国联通",m:"sh",mk:"ashare",s:"电信"},
{c:"sh600941",n:"中国移动",m:"sh",mk:"ashare",s:"电信"},
{c:"sh601728",n:"中国电信",m:"sh",mk:"ashare",s:"电信"},
{c:"sh600011",n:"华能国际",m:"sh",mk:"ashare",s:"公用事业"},
{c:"sh600023",n:"浙能电力",m:"sh",mk:"ashare",s:"公用事业"},
{c:"sh600025",n:"华能水电",m:"sh",mk:"ashare",s:"公用事业"},
{c:"sh600027",n:"华电国际",m:"sh",mk:"ashare",s:"公用事业"},
{c:"sh600674",n:"川投能源",m:"sh",mk:"ashare",s:"公用事业"},
{c:"sh600795",n:"国电电力",m:"sh",mk:"ashare",s:"公用事业"},
{c:"sh600886",n:"国投电力",m:"sh",mk:"ashare",s:"公用事业"},
{c:"sh600900",n:"长江电力",m:"sh",mk:"ashare",s:"公用事业"},
{c:"sh600905",n:"三峡能源",m:"sh",mk:"ashare",s:"公用事业"},
{c:"sh601669",n:"中国电建",m:"sh",mk:"ashare",s:"公用事业"},
{c:"sh601985",n:"中国核电",m:"sh",mk:"ashare",s:"公用事业"},
{c:"sz003816",n:"中国广核",m:"sz",mk:"ashare",s:"公用事业"},
{c:"sh600160",n:"巨化股份",m:"sh",mk:"ashare",s:"化工"},
{c:"sh600309",n:"万华化学",m:"sh",mk:"ashare",s:"化工"},
{c:"sh600426",n:"华鲁恒升",m:"sh",mk:"ashare",s:"化工"},
{c:"sz002648",n:"卫星化学",m:"sz",mk:"ashare",s:"化工"},
{c:"sh600031",n:"三一重工",m:"sh",mk:"ashare",s:"机械"},
{c:"sz000157",n:"中联重科",m:"sz",mk:"ashare",s:"机械"},
{c:"sz000338",n:"潍柴动力",m:"sz",mk:"ashare",s:"机械"},
{c:"sz000425",n:"徐工机械",m:"sz",mk:"ashare",s:"机械"},
{c:"sh601117",n:"中国化学",m:"sh",mk:"ashare",s:"基建"},
{c:"sh601186",n:"中国铁建",m:"sh",mk:"ashare",s:"基建"},
{c:"sh601390",n:"中国中铁",m:"sh",mk:"ashare",s:"基建"},
{c:"sh601668",n:"中国建筑",m:"sh",mk:"ashare",s:"基建"},
{c:"sh601868",n:"中国能建",m:"sh",mk:"ashare",s:"基建"},
{c:"sh600690",n:"海尔智家",m:"sh",mk:"ashare",s:"家电"},
{c:"sz000333",n:"美的集团",m:"sz",mk:"ashare",s:"家电"},
{c:"sz000651",n:"格力电器",m:"sz",mk:"ashare",s:"家电"},
{c:"sh600019",n:"宝钢股份",m:"sh",mk:"ashare",s:"建材"},
{c:"sh600176",n:"中国巨石",m:"sh",mk:"ashare",s:"建材"},
{c:"sh600585",n:"海螺水泥",m:"sh",mk:"ashare",s:"建材"},
{c:"sh600150",n:"中国船舶",m:"sh",mk:"ashare",s:"军工"},
{c:"sh600372",n:"中航机载",m:"sh",mk:"ashare",s:"军工"},
{c:"sh600482",n:"中国动力",m:"sh",mk:"ashare",s:"军工"},
{c:"sh600760",n:"中航沈飞",m:"sh",mk:"ashare",s:"军工"},
{c:"sh600893",n:"航发动力",m:"sh",mk:"ashare",s:"军工"},
{c:"sz000768",n:"中航西飞",m:"sz",mk:"ashare",s:"军工"},
{c:"sh600570",n:"恒生电子",m:"sh",mk:"ashare",s:"科技"},
{c:"sh600584",n:"长电科技",m:"sh",mk:"ashare",s:"科技"},
{c:"sh600745",n:"闻泰科技",m:"sh",mk:"ashare",s:"科技"},
{c:"sh603019",n:"中科曙光",m:"sh",mk:"ashare",s:"科技"},
{c:"sh688111",n:"金山办公",m:"sh",mk:"ashare",s:"科技"},
{c:"sz000063",n:"中兴通讯",m:"sz",mk:"ashare",s:"科技"},
{c:"sz000725",n:"京东方A",m:"sz",mk:"ashare",s:"科技"},
{c:"sz000977",n:"浪潮信息",m:"sz",mk:"ashare",s:"科技"},
{c:"sz002185",n:"华天科技",m:"sz",mk:"ashare",s:"科技"},
{c:"sz002475",n:"立讯精密",m:"sz",mk:"ashare",s:"科技"},
{c:"sz300433",n:"蓝思科技",m:"sz",mk:"ashare",s:"科技"},
{c:"sh600028",n:"中国石化",m:"sh",mk:"ashare",s:"能源"},
{c:"sh600346",n:"恒力石化",m:"sh",mk:"ashare",s:"能源"},
{c:"sh600938",n:"中国海油",m:"sh",mk:"ashare",s:"能源"},
{c:"sh601001",n:"中国铀业",m:"sh",mk:"ashare",s:"能源"},
{c:"sh601088",n:"中国神华",m:"sh",mk:"ashare",s:"能源"},
{c:"sh601225",n:"陕西煤业",m:"sh",mk:"ashare",s:"能源"},
{c:"sh601857",n:"中国石油",m:"sh",mk:"ashare",s:"能源"},
{c:"sh601898",n:"中煤能源",m:"sh",mk:"ashare",s:"能源"},
{c:"sz002493",n:"荣盛石化",m:"sz",mk:"ashare",s:"能源"},
{c:"sz002714",n:"牧原股份",m:"sz",mk:"ashare",s:"农牧"},
{c:"sz300498",n:"温氏股份",m:"sz",mk:"ashare",s:"农牧"},
{c:"sh510050",n:"sh510050",m:"sh",mk:"ashare",s:"其他"},
{c:"sh510300",n:"sh510300",m:"sh",mk:"ashare",s:"其他"},
{c:"sh510500",n:"sh510500",m:"sh",mk:"ashare",s:"其他"},
{c:"sh588000",n:"sh588000",m:"sh",mk:"ashare",s:"其他"},
{c:"sh601601",n:"中国太保",m:"sh",mk:"ashare",s:"其他"},
{c:"sh601628",n:"中国人寿",m:"sh",mk:"ashare",s:"其他"},
{c:"sh601800",n:"中国交建",m:"sh",mk:"ashare",s:"其他"},
{c:"sh601816",n:"京沪高铁",m:"sh",mk:"ashare",s:"其他"},
{c:"sh601989",n:"sh601989",m:"sh",mk:"ashare",s:"其他"},
{c:"sh688036",n:"传音控股",m:"sh",mk:"ashare",s:"其他"},
{c:"sh688126",n:"沪硅产业",m:"sh",mk:"ashare",s:"其他"},
{c:"sz000661",n:"sz000661",m:"sz",mk:"ashare",s:"其他"},
{c:"sz000792",n:"盐湖股份",m:"sz",mk:"ashare",s:"其他"},
{c:"sz000938",n:"紫光股份",m:"sz",mk:"ashare",s:"其他"},
{c:"sz002027",n:"分众传媒",m:"sz",mk:"ashare",s:"其他"},
{c:"sz002032",n:"sz002032",m:"sz",mk:"ashare",s:"其他"},
{c:"sz002049",n:"紫光国微",m:"sz",mk:"ashare",s:"其他"},
{c:"sz002050",n:"三花智控",m:"sz",mk:"ashare",s:"其他"},
{c:"sz002156",n:"通富微电",m:"sz",mk:"ashare",s:"其他"},
{c:"sz002179",n:"中航光电",m:"sz",mk:"ashare",s:"其他"},
{c:"sz002236",n:"大华股份",m:"sz",mk:"ashare",s:"其他"},
{c:"sz002241",n:"歌尔股份",m:"sz",mk:"ashare",s:"其他"},
{c:"sz002415",n:"海康威视",m:"sz",mk:"ashare",s:"其他"},
{c:"sz002459",n:"sz002459",m:"sz",mk:"ashare",s:"其他"},
{c:"sz002460",n:"赣锋锂业",m:"sz",mk:"ashare",s:"其他"},
{c:"sz002463",n:"沪电股份",m:"sz",mk:"ashare",s:"其他"},
{c:"sz002466",n:"天齐锂业",m:"sz",mk:"ashare",s:"其他"},
{c:"sz002600",n:"领益智造",m:"sz",mk:"ashare",s:"其他"},
{c:"sz002916",n:"深南电路",m:"sz",mk:"ashare",s:"其他"},
{c:"sz002920",n:"德赛西威",m:"sz",mk:"ashare",s:"其他"},
{c:"sz159915",n:"sz159915",m:"sz",mk:"ashare",s:"其他"},
{c:"sz300124",n:"汇川技术",m:"sz",mk:"ashare",s:"其他"},
{c:"sz300251",n:"光线传媒",m:"sz",mk:"ashare",s:"其他"},
{c:"sz300308",n:"中际旭创",m:"sz",mk:"ashare",s:"其他"},
{c:"sz300394",n:"天孚通信",m:"sz",mk:"ashare",s:"其他"},
{c:"sz300408",n:"三环集团",m:"sz",mk:"ashare",s:"其他"},
{c:"sz300502",n:"新易盛",m:"sz",mk:"ashare",s:"其他"},
{c:"sz300661",n:"圣邦股份",m:"sz",mk:"ashare",s:"其他"},
{c:"sz300803",n:"指南针",m:"sz",mk:"ashare",s:"其他"},
{c:"sh600066",n:"宇通客车",m:"sh",mk:"ashare",s:"汽车"},
{c:"sh600104",n:"上汽集团",m:"sh",mk:"ashare",s:"汽车"},
{c:"sh601127",n:"赛力斯",m:"sh",mk:"ashare",s:"汽车"},
{c:"sh601633",n:"长城汽车",m:"sh",mk:"ashare",s:"汽车"},
{c:"sh601689",n:"拓普集团",m:"sh",mk:"ashare",s:"汽车"},
{c:"sz000625",n:"长安汽车",m:"sz",mk:"ashare",s:"汽车"},
{c:"sz002594",n:"比亚迪",m:"sz",mk:"ashare",s:"汽车"},
{c:"sh600030",n:"中信证券",m:"sh",mk:"ashare",s:"券商"},
{c:"sh601066",n:"中信建投",m:"sh",mk:"ashare",s:"券商"},
{c:"sh601688",n:"华泰证券",m:"sh",mk:"ashare",s:"券商"},
{c:"sh601878",n:"浙商证券",m:"sh",mk:"ashare",s:"券商"},
{c:"sh601881",n:"中国银河",m:"sh",mk:"ashare",s:"券商"},
{c:"sh601995",n:"中金公司",m:"sh",mk:"ashare",s:"券商"},
{c:"sz000166",n:"申万宏源",m:"sz",mk:"ashare",s:"券商"},
{c:"sz000776",n:"广发证券",m:"sz",mk:"ashare",s:"券商"},
{c:"sz002736",n:"国信证券",m:"sz",mk:"ashare",s:"券商"},
{c:"sz300059",n:"东方财富",m:"sz",mk:"ashare",s:"券商"},
{c:"sh600029",n:"南方航空",m:"sh",mk:"ashare",s:"物流"},
{c:"sh600233",n:"圆通速递",m:"sh",mk:"ashare",s:"物流"},
{c:"sh601006",n:"大秦铁路",m:"sh",mk:"ashare",s:"物流"},
{c:"sh601111",n:"中国国航",m:"sh",mk:"ashare",s:"物流"},
{c:"sh601919",n:"中远海控",m:"sh",mk:"ashare",s:"物流"},
{c:"sz002352",n:"顺丰控股",m:"sz",mk:"ashare",s:"物流"},
{c:"sh600887",n:"伊利股份",m:"sh",mk:"ashare",s:"消费"},
{c:"sh601888",n:"中国中免",m:"sh",mk:"ashare",s:"消费"},
{c:"sh603288",n:"海天味业",m:"sh",mk:"ashare",s:"消费"},
{c:"sh605499",n:"东鹏饮料",m:"sh",mk:"ashare",s:"消费"},
{c:"sz000895",n:"双汇发展",m:"sz",mk:"ashare",s:"消费"},
{c:"sz300999",n:"金龙鱼",m:"sz",mk:"ashare",s:"消费"},
{c:"sh600703",n:"三安光电",m:"sh",mk:"ashare",s:"芯片"},
{c:"sh603501",n:"豪威集团",m:"sh",mk:"ashare",s:"芯片"},
{c:"sh603986",n:"兆易创新",m:"sh",mk:"ashare",s:"芯片"},
{c:"sh688008",n:"澜起科技",m:"sh",mk:"ashare",s:"芯片"},
{c:"sh688012",n:"中微公司",m:"sh",mk:"ashare",s:"芯片"},
{c:"sh688041",n:"海光信息",m:"sh",mk:"ashare",s:"芯片"},
{c:"sh688047",n:"龙芯中科",m:"sh",mk:"ashare",s:"芯片"},
{c:"sh688981",n:"中芯国际",m:"sh",mk:"ashare",s:"芯片"},
{c:"sz002371",n:"北方华创",m:"sz",mk:"ashare",s:"芯片"},
{c:"sz301269",n:"华大九天",m:"sz",mk:"ashare",s:"芯片"},
{c:"sh600438",n:"通威股份",m:"sh",mk:"ashare",s:"新能源"},
{c:"sh601012",n:"隆基绿能",m:"sh",mk:"ashare",s:"新能源"},
{c:"sh605117",n:"德业股份",m:"sh",mk:"ashare",s:"新能源"},
{c:"sh688223",n:"晶科能源",m:"sh",mk:"ashare",s:"新能源"},
{c:"sh688303",n:"大全能源",m:"sh",mk:"ashare",s:"新能源"},
{c:"sh688472",n:"阿特斯",m:"sh",mk:"ashare",s:"新能源"},
{c:"sz002074",n:"国轩高科",m:"sz",mk:"ashare",s:"新能源"},
{c:"sz002709",n:"天赐材料",m:"sz",mk:"ashare",s:"新能源"},
{c:"sz300014",n:"亿纬锂能",m:"sz",mk:"ashare",s:"新能源"},
{c:"sz300274",n:"阳光电源",m:"sz",mk:"ashare",s:"新能源"},
{c:"sz300750",n:"宁德时代",m:"sz",mk:"ashare",s:"新能源"},
{c:"sh600085",n:"同仁堂",m:"sh",mk:"ashare",s:"医药"},
{c:"sh600196",n:"复星医药",m:"sh",mk:"ashare",s:"医药"},
{c:"sh600276",n:"恒瑞医药",m:"sh",mk:"ashare",s:"医药"},
{c:"sh600436",n:"片仔癀",m:"sh",mk:"ashare",s:"医药"},
{c:"sh603259",n:"药明康德",m:"sh",mk:"ashare",s:"医药"},
{c:"sh603392",n:"万泰生物",m:"sh",mk:"ashare",s:"医药"},
{c:"sh688271",n:"联影医疗",m:"sh",mk:"ashare",s:"医药"},
{c:"sz000538",n:"云南白药",m:"sz",mk:"ashare",s:"医药"},
{c:"sz000963",n:"华东医药",m:"sz",mk:"ashare",s:"医药"},
{c:"sz000999",n:"华润三九",m:"sz",mk:"ashare",s:"医药"},
{c:"sz002422",n:"科伦药业",m:"sz",mk:"ashare",s:"医药"},
{c:"sz300015",n:"爱尔眼科",m:"sz",mk:"ashare",s:"医药"},
{c:"sz300122",n:"智飞生物",m:"sz",mk:"ashare",s:"医药"},
{c:"sz300760",n:"迈瑞医疗",m:"sz",mk:"ashare",s:"医药"},
{c:"sz300832",n:"新产业",m:"sz",mk:"ashare",s:"医药"},
{c:"sz300896",n:"爱美客",m:"sz",mk:"ashare",s:"医药"},
{c:"sh600000",n:"浦发银行",m:"sh",mk:"ashare",s:"银行"},
{c:"sh600015",n:"华夏银行",m:"sh",mk:"ashare",s:"银行"},
{c:"sh600016",n:"民生银行",m:"sh",mk:"ashare",s:"银行"},
{c:"sh600036",n:"招商银行",m:"sh",mk:"ashare",s:"银行"},
{c:"sh601009",n:"南京银行",m:"sh",mk:"ashare",s:"银行"},
{c:"sh601166",n:"兴业银行",m:"sh",mk:"ashare",s:"银行"},
{c:"sh601169",n:"北京银行",m:"sh",mk:"ashare",s:"银行"},
{c:"sh601229",n:"上海银行",m:"sh",mk:"ashare",s:"银行"},
{c:"sh601288",n:"农业银行",m:"sh",mk:"ashare",s:"银行"},
{c:"sh601328",n:"交通银行",m:"sh",mk:"ashare",s:"银行"},
{c:"sh601398",n:"工商银行",m:"sh",mk:"ashare",s:"银行"},
{c:"sh601658",n:"邮储银行",m:"sh",mk:"ashare",s:"银行"},
{c:"sh601818",n:"光大银行",m:"sh",mk:"ashare",s:"银行"},
{c:"sh601838",n:"成都银行",m:"sh",mk:"ashare",s:"银行"},
{c:"sh601916",n:"浙商银行",m:"sh",mk:"ashare",s:"银行"},
{c:"sh601939",n:"建设银行",m:"sh",mk:"ashare",s:"银行"},
{c:"sh601988",n:"中国银行",m:"sh",mk:"ashare",s:"银行"},
{c:"sz000001",n:"平安银行",m:"sz",mk:"ashare",s:"银行"},
{c:"sh600111",n:"北方稀土",m:"sh",mk:"ashare",s:"有色"},
{c:"sh600219",n:"南山铝业",m:"sh",mk:"ashare",s:"有色"},
{c:"sh600362",n:"江西铜业",m:"sh",mk:"ashare",s:"有色"},
{c:"sh600489",n:"中金黄金",m:"sh",mk:"ashare",s:"有色"},
{c:"sh600547",n:"山东黄金",m:"sh",mk:"ashare",s:"有色"},
{c:"sh600549",n:"厦门钨业",m:"sh",mk:"ashare",s:"有色"},
{c:"sh601899",n:"紫金矿业",m:"sh",mk:"ashare",s:"有色"},
{c:"sh603993",n:"洛阳钼业",m:"sh",mk:"ashare",s:"有色"},
{c:"sz000630",n:"铜陵有色",m:"sz",mk:"ashare",s:"有色"},
{c:"sz000807",n:"云铝股份",m:"sz",mk:"ashare",s:"有色"},
{c:"sz002230",n:"科大讯飞",m:"sz",mk:"ashare",s:"AI"},
{c:"sz300033",n:"同花顺",m:"sz",mk:"ashare",s:"AI"},
{c:"sz300418",n:"昆仑万维",m:"sz",mk:"ashare",s:"AI"},
{c:"00700",n:"腾讯控股",m:"hk",mk:"hkshare"},
{c:"09988",n:"阿里巴巴-SW",m:"hk",mk:"hkshare"},
{c:"09999",n:"网易-S",m:"hk",mk:"hkshare"},
{c:"03690",n:"美团-W",m:"hk",mk:"hkshare"},
{c:"09618",n:"京东集团-SW",m:"hk",mk:"hkshare"},
{c:"01810",n:"小米集团-W",m:"hk",mk:"hkshare"},
{c:"09888",n:"百度集团-SW",m:"hk",mk:"hkshare"},
{c:"02015",n:"理想汽车-W",m:"hk",mk:"hkshare"},
{c:"09866",n:"蔚来-SW",m:"hk",mk:"hkshare"},
{c:"09868",n:"小鹏汽车-W",m:"hk",mk:"hkshare"},
{c:"01211",n:"比亚迪股份",m:"hk",mk:"hkshare"},
{c:"02269",n:"药明生物",m:"hk",mk:"hkshare"},
{c:"02382",n:"舜宇光学科技",m:"hk",mk:"hkshare"},
{c:"02020",n:"安踏体育",m:"hk",mk:"hkshare"},
{c:"02331",n:"李宁",m:"hk",mk:"hkshare"},
{c:"09626",n:"哔哩哔哩-W",m:"hk",mk:"hkshare"},
{c:"09660",n:"地平线机器人-W",m:"hk",mk:"hkshare"},
{c:"01347",n:"华虹半导体",m:"hk",mk:"hkshare"},
{c:"00981",n:"中芯国际",m:"hk",mk:"hkshare"},
{c:"00175",n:"吉利汽车",m:"hk",mk:"hkshare"},
{c:"00388",n:"香港交易所",m:"hk",mk:"hkshare"},
{c:"00005",n:"汇丰控股",m:"hk",mk:"hkshare"},
{c:"01299",n:"友邦保险",m:"hk",mk:"hkshare"},
{c:"01398",n:"工商银行",m:"hk",mk:"hkshare"},
{c:"03988",n:"中国银行",m:"hk",mk:"hkshare"},
{c:"00883",n:"中国海洋石油",m:"hk",mk:"hkshare"},
{c:"00941",n:"中国移动",m:"hk",mk:"hkshare"},
{c:"00728",n:"中国电信",m:"hk",mk:"hkshare"},
{c:"02057",n:"中通快递-W",m:"hk",mk:"hkshare"},
{c:"09901",n:"新东方-S",m:"hk",mk:"hkshare"},
{c:"02628",n:"中国人寿",m:"hk",mk:"hkshare"},
{c:"02318",n:"中国平安",m:"hk",mk:"hkshare"},
{c:"01024",n:"快手-W",m:"hk",mk:"hkshare"},
{c:"01833",n:"平安好医生",m:"hk",mk:"hkshare"},
{c:"06098",n:"碧桂园服务",m:"hk",mk:"hkshare"},
{c:"06060",n:"众安在线",m:"hk",mk:"hkshare"},
{c:"01928",n:"金沙中国",m:"hk",mk:"hkshare"},
{c:"00027",n:"银河娱乐",m:"hk",mk:"hkshare"},
{c:"02828",n:"恒生中国企业ETF",m:"hk",mk:"hkshare"},
{c:"02800",n:"盈富基金",m:"hk",mk:"hkshare"},
{c:"00780",n:"同程旅行",m:"hk",mk:"hkshare",p:"Tongcheng"},
{c:"09698",n:"万国数据-SW",m:"hk",mk:"hkshare",p:"GDS"},
{c:"06690",n:"海尔智家",m:"hk",mk:"hkshare",p:"Haier"},
{c:"01057",n:"浙江沪杭甬",m:"hk",mk:"hkshare"},
{c:"06862",n:"海底捞",m:"hk",mk:"hkshare",p:"Haidilao"},
{c:"09633",n:"农夫山泉",m:"hk",mk:"hkshare",p:"Nongfu"},
{c:"06186",n:"中国飞鹤",m:"hk",mk:"hkshare"},
{c:"02018",n:"瑞声科技",m:"hk",mk:"hkshare"},
{c:"00288",n:"万洲国际",m:"hk",mk:"hkshare",p:"WHGroup"},
{c:"02319",n:"蒙牛乳业",m:"hk",mk:"hkshare",p:"Mengniu"},
{c:"00168",n:"青岛啤酒",m:"hk",mk:"hkshare",p:"Tsingtao"},
{c:"06185",n:"康龙化成",m:"hk",mk:"hkshare"},
{c:"01093",n:"石药集团",m:"hk",mk:"hkshare"},
{c:"01177",n:"中国生物制药",m:"hk",mk:"hkshare"},
{c:"00020",n:"商汤-W",m:"hk",mk:"hkshare",p:"SenseTime"},
{c:"09863",n:"零跑汽车",m:"hk",mk:"hkshare"},
{c:"09810",n:"极氪",m:"hk",mk:"hkshare"},
{c:"02601",n:"中国太保",m:"hk",mk:"hkshare"},
{c:"01658",n:"邮储银行",m:"hk",mk:"hkshare"},
{c:"03968",n:"招商银行",m:"hk",mk:"hkshare",p:"CMB"},
{c:"00998",n:"中信银行",m:"hk",mk:"hkshare"},
{c:"06886",n:"HTSC",m:"hk",mk:"hkshare"},
{c:"06030",n:"中信证券",m:"hk",mk:"hkshare"},
{c:"00016",n:"新鸿基地产",m:"hk",mk:"hkshare",p:"SHKProps"},
{c:"00001",n:"长和",m:"hk",mk:"hkshare",p:"CKHutchison"},
{c:"00002",n:"中电控股",m:"hk",mk:"hkshare",p:"CLP"},
{c:"00003",n:"香港中华煤气",m:"hk",mk:"hkshare"},
{c:"00006",n:"电能实业",m:"hk",mk:"hkshare"},
{c:"00011",n:"恒生银行",m:"hk",mk:"hkshare",p:"HangSengBank"},
{c:"00066",n:"港铁公司",m:"hk",mk:"hkshare",p:"MTR"},
{c:"0823",n:"领展房产基金",m:"hk",mk:"hkshare",p:"LinkREIT"},
{c:"01209",n:"华润万象生活",m:"hk",mk:"hkshare"},
{c:"02333",n:"长城汽车",m:"hk",mk:"hkshare",p:"GreatWall"},
{c:"02238",n:"广汽集团",m:"hk",mk:"hkshare"},
{c:"00753",n:"中国国航",m:"hk",mk:"hkshare"},
{c:"01109",n:"华润置地",m:"hk",mk:"hkshare"},
{c:"00669",n:"创科实业",m:"hk",mk:"hkshare",p:"TTI"},
{c:"00522",n:"ASMPT",m:"hk",mk:"hkshare"},
{c:"AAPL",n:"Apple Inc.",m:"us",mk:"usshare",s:"科技",p:"苹果"},
{c:"MSFT",n:"Microsoft",m:"us",mk:"usshare",s:"科技",p:"微软"},
{c:"GOOGL",n:"Alphabet (Google)",m:"us",mk:"usshare",s:"科技",p:"谷歌"},
{c:"AMZN",n:"Amazon",m:"us",mk:"usshare",s:"电商",p:"亚马逊"},
{c:"NVDA",n:"NVIDIA",m:"us",mk:"usshare",s:"芯片",p:"英伟达"},
{c:"META",n:"Meta Platforms",m:"us",mk:"usshare",s:"社交",p:"脸书"},
{c:"TSLA",n:"Tesla",m:"us",mk:"usshare",s:"汽车",p:"特斯拉"},
{c:"BRK.B",n:"Berkshire Hathaway",m:"us",mk:"usshare",s:"投资",p:"伯克希尔"},
{c:"JPM",n:"JPMorgan Chase",m:"us",mk:"usshare",s:"银行",p:"摩根大通"},
{c:"V",n:"Visa",m:"us",mk:"usshare",s:"支付"},
{c:"JNJ",n:"Johnson & Johnson",m:"us",mk:"usshare",s:"医药",p:"强生"},
{c:"WMT",n:"Walmart",m:"us",mk:"usshare",s:"零售",p:"沃尔玛"},
{c:"PG",n:"Procter & Gamble",m:"us",mk:"usshare",s:"消费品",p:"宝洁"},
{c:"XOM",n:"Exxon Mobil",m:"us",mk:"usshare",s:"能源",p:"埃克森美孚"},
{c:"UNH",n:"UnitedHealth",m:"us",mk:"usshare",s:"医疗"},
{c:"COST",n:"Costco",m:"us",mk:"usshare",s:"零售",p:"好市多"},
{c:"HD",n:"Home Depot",m:"us",mk:"usshare",s:"零售",p:"家得宝"},
{c:"AVGO",n:"Broadcom",m:"us",mk:"usshare",s:"芯片"},
{c:"CRM",n:"Salesforce",m:"us",mk:"usshare",s:"软件"},
{c:"AMD",n:"AMD",m:"us",mk:"usshare",s:"芯片"},
{c:"NFLX",n:"Netflix",m:"us",mk:"usshare",s:"流媒体",p:"奈飞"},
{c:"DIS",n:"Walt Disney",m:"us",mk:"usshare",s:"娱乐",p:"迪士尼"},
{c:"BAC",n:"Bank of America",m:"us",mk:"usshare",s:"银行",p:"美国银行"},
{c:"KO",n:"Coca-Cola",m:"us",mk:"usshare",s:"饮料",p:"可口可乐"},
{c:"PEP",n:"PepsiCo",m:"us",mk:"usshare",s:"饮料",p:"百事"},
{c:"ADBE",n:"Adobe",m:"us",mk:"usshare",s:"软件"},
{c:"QCOM",n:"Qualcomm",m:"us",mk:"usshare",s:"芯片",p:"高通"},
{c:"TXN",n:"Texas Instruments",m:"us",mk:"usshare",s:"芯片"},
{c:"ASML",n:"ASML Holding",m:"us",mk:"usshare",s:"设备",p:"阿斯麦"},
{c:"BABA",n:"Alibaba Group",m:"us",mk:"usshare",s:"电商",p:"阿里巴巴"},
{c:"JD",n:"JD.com",m:"us",mk:"usshare",s:"电商",p:"京东"},
{c:"PDD",n:"PDD Holdings",m:"us",mk:"usshare",s:"电商",p:"拼多多"},
{c:"BIDU",n:"Baidu",m:"us",mk:"usshare",s:"搜索",p:"百度"},
{c:"NIO",n:"NIO Inc.",m:"us",mk:"usshare",s:"汽车",p:"蔚来"},
{c:"XPEV",n:"XPeng Inc.",m:"us",mk:"usshare",s:"汽车",p:"小鹏"},
{c:"LI",n:"Li Auto",m:"us",mk:"usshare",s:"汽车",p:"理想"},
{c:"TME",n:"Tencent Music",m:"us",mk:"usshare",s:"音乐",p:"腾讯音乐"},
{c:"BILI",n:"Bilibili",m:"us",mk:"usshare",s:"视频",p:"哔哩哔哩"},
{c:"NTES",n:"NetEase",m:"us",mk:"usshare",s:"游戏",p:"网易"},
{c:"ZTO",n:"ZTO Express",m:"us",mk:"usshare",s:"物流",p:"中通快递"},
{c:"BEKE",n:"KE Holdings",m:"us",mk:"usshare",s:"房产",p:"贝壳"},
{c:"YUMC",n:"Yum China",m:"us",mk:"usshare",s:"餐饮",p:"百胜中国"},
{c:"DIDIY",n:"DiDi Global",m:"us",mk:"usshare",s:"出行",p:"滴滴"},
{c:"FUTU",n:"Futu Holdings",m:"us",mk:"usshare",s:"券商",p:"富途"},
{c:"SPY",n:"SPDR S&P 500 ETF",m:"us",mk:"usshare",s:"ETF"},
{c:"QQQ",n:"Invesco QQQ Trust",m:"us",mk:"usshare",s:"ETF"},
{c:"IWM",n:"iShares Russell 2000",m:"us",mk:"usshare",s:"ETF"},
{c:"GLD",n:"SPDR Gold Trust",m:"us",mk:"usshare",s:"黄金"},
{c:"VOO",n:"Vanguard S&P 500",m:"us",mk:"usshare",s:"ETF"},
{c:"INTC",n:"Intel",m:"us",mk:"usshare",s:"芯片",p:"英特尔"},
{c:"ORCL",n:"Oracle",m:"us",mk:"usshare",s:"软件",p:"甲骨文"},
{c:"CSCO",n:"Cisco",m:"us",mk:"usshare",s:"科技",p:"思科"},
{c:"IBM",n:"IBM",m:"us",mk:"usshare",s:"科技"},
{c:"SAP",n:"SAP SE",m:"us",mk:"usshare",s:"软件"},
{c:"NOW",n:"ServiceNow",m:"us",mk:"usshare",s:"软件"},
{c:"UBER",n:"Uber",m:"us",mk:"usshare",s:"出行"},
{c:"ABNB",n:"Airbnb",m:"us",mk:"usshare",s:"出行"},
{c:"SQ",n:"Block (Square)",m:"us",mk:"usshare",s:"支付"},
{c:"PYPL",n:"PayPal",m:"us",mk:"usshare",s:"支付"},
{c:"SNAP",n:"Snap Inc.",m:"us",mk:"usshare",s:"社交"},
{c:"PLTR",n:"Palantir",m:"us",mk:"usshare",s:"软件"},
{c:"MU",n:"Micron",m:"us",mk:"usshare",s:"芯片",p:"美光"},
{c:"ARM",n:"Arm Holdings",m:"us",mk:"usshare",s:"芯片"},
{c:"TSM",n:"TSMC (ADR)",m:"us",mk:"usshare",s:"芯片",p:"台积电"},
{c:"MRK",n:"Merck & Co.",m:"us",mk:"usshare",s:"医药",p:"默克"},
{c:"PFE",n:"Pfizer",m:"us",mk:"usshare",s:"医药",p:"辉瑞"},
{c:"ABBV",n:"AbbVie",m:"us",mk:"usshare",s:"医药"},
{c:"LLY",n:"Eli Lilly",m:"us",mk:"usshare",s:"医药",p:"礼来"},
{c:"NKE",n:"Nike",m:"us",mk:"usshare",s:"消费品",p:"耐克"},
{c:"SBUX",n:"Starbucks",m:"us",mk:"usshare",s:"消费",p:"星巴克"},
{c:"MCD",n:"McDonald's",m:"us",mk:"usshare",s:"餐饮",p:"麦当劳"},
{c:"BA",n:"Boeing",m:"us",mk:"usshare",s:"航天",p:"波音"},
{c:"GE",n:"GE Aerospace",m:"us",mk:"usshare",s:"工业"},
{c:"CAT",n:"Caterpillar",m:"us",mk:"usshare",s:"机械"},
{c:"CMG",n:"Chipotle",m:"us",mk:"usshare",s:"餐饮"}
];

module.exports = STOCK_DB;
